"""Filter a photogrammetric point cloud to a ground surface.

An implementation of the Simple Morphological Filter (Pingel, Clarke and
McBride, 2013). PDAL ships one; this project cannot install PDAL on the
machines it is being built on, and a filter written here is one the team can
read, test against surfaces whose answer is known, and explain at the showcase.

**What this produces is not a LiDAR DTM.** D2 established that the City of
Melbourne cloud is photogrammetric — generated by ContextCapture, described by
a ground sample distance. A laser reaches the ground through gaps in a tree
canopy; a camera cannot. Under dense vegetation there are no ground points to
keep, so the surface there is interpolated across the gap rather than measured.
Streets are open to the sky and are measured, which is the part the scenario
model routes water over. `filled_fraction` in the result reports how much of
the surface was interpolated, and the provenance note must carry it.

The filter works on a raster rather than on points because that is what the
scenario engine consumes, and because the morphological step is defined on one.

One known edge effect. Opening returns a planar surface exactly, which is what
keeps the filter from flattening a street — but only on an unbounded plane. At
the uphill edge of a finite extent the structuring element cannot fit past the
boundary, so a band of `max_window_m / 2` there is shaved. At the gradients in
the demonstration extent the shaving stays far below the threshold and nothing
is flagged; it is documented because the correct fix is to filter a buffered
extent and crop, and whoever adds that needs to know how wide to make it.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy import ndimage


#: Widest opening the filter reaches, and so the widest roof it can remove.
#:
#: Measured on the demonstration extent rather than guessed. Widening the window
#: removes steadily more, and the marginal hectare goes flat at about 26 m —
#: 12→18 m removes a further 5.8 ha, 18→26 m a further 2.2 ha, and every step
#: after that a near-constant ~1 ha, which is the signature of terrain being
#: shaved rather than buildings being found.
#:
#: Of the 2.2 ha that 26 m removes and 18 m does not, 54% stands more than two
#: metres above the ground: large roofs. The rest is ground rejected
#: unnecessarily. That trade is worth taking because the two errors do not cost
#: the same. A rejected ground cell is interpolated from its neighbours a metre
#: away and lands within a few centimetres. A roof that survives is a three- to
#: eight-metre plateau in the middle of the flow routing, and water will run
#: around it.
DEFAULT_MAX_WINDOW_M = 26.0

#: Tolerated fall per step of the window, as a fraction of the step. The SMRF
#: paper's own default.
DEFAULT_SLOPE_THRESHOLD = 0.15


class GroundError(Exception):
    pass


@dataclass(frozen=True)
class GroundSurface:
    """A filtered ground surface on a regular grid, north-up."""

    elevation: np.ndarray
    """Metres, shape (rows, cols). Row 0 is the northern edge."""

    observed: np.ndarray
    """True where a ground point was measured, False where it was interpolated."""

    min_e: float
    min_n: float
    cell_size_m: float

    @property
    def shape(self) -> tuple[int, int]:
        return self.elevation.shape

    @property
    def filled_fraction(self) -> float:
        """How much of the surface is interpolation rather than measurement."""
        return float(1.0 - self.observed.mean())

    def elevation_at(self, easting: float, northing: float) -> float:
        rows, cols = self.elevation.shape
        col = int((easting - self.min_e) // self.cell_size_m)
        row = rows - 1 - int((northing - self.min_n) // self.cell_size_m)
        if not (0 <= row < rows and 0 <= col < cols):
            raise GroundError(f"({easting}, {northing}) is outside the surface")
        return float(self.elevation[row, col])


def _disk(radius: int) -> np.ndarray:
    size = 2 * radius + 1
    y, x = np.ogrid[-radius : radius + 1, -radius : radius + 1]
    return (x * x + y * y) <= radius * radius + 1e-9


def minimum_surface(
    points: np.ndarray,
    min_e: float,
    min_n: float,
    max_e: float,
    max_n: float,
    cell_size_m: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Lowest point in each cell, and where a point fell at all.

    The lowest return in a cell is the best available estimate of the ground
    before any filtering: everything above it is something standing on it.
    """
    if cell_size_m <= 0:
        raise GroundError("cell size must be positive")
    cols = int(round((max_e - min_e) / cell_size_m))
    rows = int(round((max_n - min_n) / cell_size_m))
    if rows < 1 or cols < 1:
        raise GroundError("the extent is smaller than one cell")

    x, y, z = points[:, 0], points[:, 1], points[:, 2]
    inside = (x >= min_e) & (x < max_e) & (y >= min_n) & (y < max_n)
    x, y, z = x[inside], y[inside], z[inside]

    col = ((x - min_e) / cell_size_m).astype(np.intp)
    row = rows - 1 - ((y - min_n) / cell_size_m).astype(np.intp)
    flat = row * cols + col

    # Write the points into the grid from highest to lowest and let the last
    # write win, which leaves the minimum. `np.minimum.at` says this more
    # plainly but runs an order of magnitude slower, and the demonstration
    # extent holds 6.6 million points.
    surface = np.full(rows * cols, np.inf)
    descending = np.argsort(-z, kind="stable")
    surface[flat[descending]] = z[descending]

    observed = np.isfinite(surface)
    return surface.reshape(rows, cols), observed.reshape(rows, cols)


def fill_holes(surface: np.ndarray, observed: np.ndarray) -> np.ndarray:
    """Fill unobserved cells from the nearest observed one.

    Nearest-neighbour rather than a smooth interpolation on purpose: it does not
    invent a gradient across a gap, and every filled cell is recorded in
    `observed` so the interface can say the surface there was not measured.
    """
    if not observed.any():
        raise GroundError("no cell in the extent contains a point")
    if observed.all():
        return surface.copy()
    _, nearest = ndimage.distance_transform_edt(~observed, return_indices=True)
    return surface[tuple(nearest)]


def object_mask(
    surface: np.ndarray,
    cell_size_m: float,
    *,
    max_window_m: float = DEFAULT_MAX_WINDOW_M,
    slope_threshold: float = DEFAULT_SLOPE_THRESHOLD,
) -> np.ndarray:
    """Cells standing on the ground rather than being it.

    Progressive morphological opening: the surface is opened at each radius in
    turn, and a cell that drops between one opening and the next is holding
    something up that the wider window has just removed.

    The threshold is `slope_threshold` times the amount the window **grew** at
    that step, not times its total width. That distinction is the whole filter.
    A threshold proportional to total width grows faster than buildings get
    tall, so a wide roof stays under it and survives; the per-step form keeps a
    constant tolerance and catches it. Terrain is safe from the constant
    tolerance for a different reason: opening a planar surface with a flat
    structuring element returns it exactly, so a street on a 10% grade drops by
    nothing at any radius, however tight the threshold.
    """
    if not 0 < slope_threshold < 1:
        raise GroundError("the slope threshold must be a fraction between 0 and 1")

    max_radius = max(1, int(round(max_window_m / cell_size_m / 2)))
    step_m = 2 * cell_size_m  # each radius widens the window by one cell either side
    tolerance = slope_threshold * step_m

    is_object = np.zeros(surface.shape, dtype=bool)
    current = surface
    for radius in range(1, max_radius + 1):
        opened = ndimage.grey_opening(current, footprint=_disk(radius), mode="nearest")
        is_object |= (current - opened) > tolerance
        current = opened

    return is_object


def build_ground_surface(
    points: np.ndarray,
    min_e: float,
    min_n: float,
    max_e: float,
    max_n: float,
    *,
    cell_size_m: float = 1.0,
    max_window_m: float = DEFAULT_MAX_WINDOW_M,
    slope_threshold: float = DEFAULT_SLOPE_THRESHOLD,
    min_measured_fraction: float = 0.05,
) -> GroundSurface:
    """Produce a ground surface from a point cloud over the given extent.

    `min_measured_fraction` is the point below which the output stops being a
    measured surface and becomes an interpolation between a handful of cells.
    It is a declared tolerance rather than a hidden one: raise it for an extent
    that should be well covered, lower it deliberately and knowingly. The
    default of 5% only catches a build that has gone wrong — a tile that failed
    to download, an extent in the wrong projection, a threshold set so low the
    filter rejected the ground itself.
    """
    surface, observed = minimum_surface(points, min_e, min_n, max_e, max_n, cell_size_m)
    filled = fill_holes(surface, observed)
    objects = object_mask(
        filled, cell_size_m, max_window_m=max_window_m, slope_threshold=slope_threshold
    )

    # An object cell has no ground measurement, so it is filled from the ground
    # around it — the same treatment as a cell no point reached, and recorded
    # the same way.
    kept = observed & ~objects
    measured = float(kept.mean())
    if measured < min_measured_fraction:
        raise GroundError(
            f"only {measured:.1%} of the extent has a measured ground cell, below the "
            f"{min_measured_fraction:.1%} this build accepts; the result would be interpolation, "
            "not a surface"
        )
    elevation = fill_holes(np.where(kept, filled, np.inf), kept)
    return GroundSurface(elevation, kept, min_e, min_n, cell_size_m)
